"""Make corporate_admin_id nullable in spacenodes

Revision ID: 01fcfe2512a6
Revises: 0581da68b2ba
Create Date: 2025-04-30 04:15:46.652205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fcfe2512a6'
down_revision: Union[str, None] = '0581da68b2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.alter_column('spacenodes', 'corporate_admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spacenodes', 'corporate_admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    # ### end Alembic commands ###
