"""add_total_workstations_to_spacenode

Revision ID: 1920f7bb20b0
Revises: 38194ae977c2
Create Date: 2025-06-30 07:32:31.956461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1920f7bb20b0'
down_revision: Union[str, None] = '38194ae977c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spacenodes', sa.Column('total_workstations', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spacenodes', 'total_workstations')
    # ### end Alembic commands ###
