"""add_space_id_to_startup_and_relationship

Revision ID: 2a94457f8436
Revises: c421022fb1a2
Create Date: 2025-05-23 09:32:33.634894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a94457f8436'
down_revision: Union[str, None] = 'c421022fb1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('space_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_startups_space_id'), 'startups', ['space_id'], unique=False)
    op.create_foreign_key(
        'fk_startups_space_id_spacenodes',  # Constraint name
        'startups', 'spacenodes',
        ['space_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_startups_space_id_spacenodes', 'startups', type_='foreignkey')
    op.drop_index(op.f('ix_startups_space_id'), table_name='startups')
    op.drop_column('startups', 'space_id')
    # ### end Alembic commands ###
