"""consolidated_initial_migration

Revision ID: 2d953f697500
Revises: 
Create Date: 2025-06-30 03:48:32.602576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d953f697500'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    startupstage_enum = sa.Enum('IDEA', 'PRE_SEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C', 'GROWTH', name='startupstage')
    startupstage_enum.create(op.get_bind(), checkfirst=True)

    teamsize_enum = sa.Enum('ONE', 'TWO_TO_FIVE', 'EXTRA_SMALL', 'SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='teamsize')
    teamsize_enum.create(op.get_bind(), checkfirst=True)

    userstatus_enum = sa.Enum('PENDING_VERIFICATION', 'WAITLISTED', 'ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus')
    userstatus_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('startups', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('industry_focus', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('mission', sa.Text(), nullable=True))
    op.add_column('startups', sa.Column('stage', startupstage_enum, nullable=True))
    op.add_column('startups', sa.Column('team_size', teamsize_enum, nullable=True))
    op.add_column('startups', sa.Column('looking_for', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('startups', sa.Column('social_media_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('startups', sa.Column('pitch_deck_url', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('member_slots_used', sa.Integer(), nullable=False))
    op.alter_column('startups', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('startups', 'status',
               existing_type=sa.VARCHAR(),
               type_=userstatus_enum,
               existing_nullable=False,
               postgresql_using='status::userstatus')
    op.alter_column('startups', 'member_slots_allocated',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_startups_space_id'), 'startups', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startups_space_id'), table_name='startups')
    op.alter_column('startups', 'member_slots_allocated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('startups', 'status',
               existing_type=sa.Enum('PENDING_VERIFICATION', 'WAITLISTED', 'ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('startups', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('startups', 'member_slots_used')
    op.drop_column('startups', 'pitch_deck_url')
    op.drop_column('startups', 'social_media_links')
    op.drop_column('startups', 'looking_for')
    op.drop_column('startups', 'team_size')
    op.drop_column('startups', 'stage')
    op.drop_column('startups', 'mission')
    op.drop_column('startups', 'industry_focus')
    op.drop_column('startups', 'logo_url')

    sa.Enum(name='startupstage').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='teamsize').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
