"""add is_profile_complete to user profile

Revision ID: 33b3dd732ecc
Revises: 9b153f9e1919
Create Date: 2025-07-05 14:43:57.561480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3dd732ecc'
down_revision: Union[str, None] = '9b153f9e1919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    op.execute('UPDATE user_profiles SET is_profile_complete = false')
    op.alter_column('user_profiles', 'is_profile_complete', nullable=False)
    op.drop_column('user_profiles', 'profile_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'is_profile_complete')
    # ### end Alembic commands ###
