"""add_address_to_spacenode

Revision ID: 38194ae977c2
Revises: e2f266b3d490
Create Date: 2025-06-30 07:24:37.007238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38194ae977c2'
down_revision: Union[str, None] = 'e2f266b3d490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spacenodes', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spacenodes', 'address')
    # ### end Alembic commands ###
