"""Add reference and link to Notification

Revision ID: 61285376d591
Revises: 08eced71251f
Create Date: 2025-05-13 05:52:58.429788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61285376d591'
down_revision: Union[str, None] = '08eced71251f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_reference'), 'notifications', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_reference'), table_name='notifications')
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'reference')
    # ### end Alembic commands ###
