"""Add space_id to users table

Revision ID: 6584e07b26cc
Revises: 362919f61f47
Create Date: 2025-04-26 11:42:14.838280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6584e07b26cc'
down_revision: str | None = '362919f61f47'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Operation already handled by revision 362919f61f47
    # op.add_column('users', sa.Column('space_id', sa.Integer(), nullable=True))
    # op.create_index(op.f('ix_users_space_id'), 'users', ['space_id'], unique=False)
    # op.create_foreign_key('users_space_id_fkey', 'users', 'spacenodes', ['space_id'], ['id'])
    pass # Indicate no operation needed in this revision anymore
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Operation already handled by revision 362919f61f47
    # op.drop_constraint('users_space_id_fkey', 'users', type_='foreignkey')
    # op.drop_index(op.f('ix_users_space_id'), table_name='users')
    # op.drop_column('users', 'space_id')
    pass # Indicate no operation needed in this revision anymore
    # ### end Alembic commands ###
