"""Add user profile table and relationship

Revision ID: 6e42b588d2b7
Revises: bd906d8dba40
Create Date: 2025-04-20 16:44:58.310022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e42b588d2b7'
down_revision: Union[str, None] = 'bd906d8dba40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('contact_info_visibility', sa.Enum('PRIVATE', 'CONNECTIONS', 'PUBLIC', name='contact_visibility_enum'), nullable=False),
    sa.Column('skills_expertise', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('industry_focus', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('project_interests_goals', sa.Text(), nullable=True),
    sa.Column('collaboration_preferences', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tools_technologies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('linkedin_profile_url', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
