"""Add ondelete=CASCADE to Notification.related_entity_id

Revision ID: 7283120610e2
Revises: 9667cae9f7d0
Create Date: 2025-07-07 02:41:53.039360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7283120610e2'
down_revision: Union[str, None] = '9667cae9f7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_related_entity_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['related_entity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_related_entity_id_fkey'), 'notifications', 'users', ['related_entity_id'], ['id'])
    # ### end Alembic commands ###
