"""add_approval_acceptance_to_invitations

Revision ID: 835b07ae6f4e
Revises: a0f683693a70
Create Date: 2024-05-26 12:00:00.000000 # Placeholder, will be updated by Alembic

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835b07ae6f4e'
down_revision: Union[str, None] = 'a0f683693a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('approved_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_invitations_approved_by_admin_id_users',
        'invitations', 'users',
        ['approved_by_admin_id'], ['id']
    )

    op.add_column('invitations', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('accepted_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_invitations_accepted_by_user_id_users',
        'invitations', 'users',
        ['accepted_by_user_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invitations_accepted_by_user_id_users', 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'accepted_by_user_id')
    op.drop_column('invitations', 'accepted_at')

    op.drop_constraint('fk_invitations_approved_by_admin_id_users', 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'approved_by_admin_id')
    # ### end Alembic commands ###
