"""Add ondelete=CASCADE to User.startup_id

Revision ID: 934a5a4cf1f3
Revises: bbd2e8d51ecc
Create Date: 2025-07-06 15:46:09.211583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '934a5a4cf1f3'
down_revision: Union[str, None] = 'bbd2e8d51ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_constraint(op.f('users_startup_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'startups', ['startup_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_startup_id_fkey'), 'users', 'startups', ['startup_id'], ['id'])
    op.add_column('conversations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
