"""Add ondelete=CASCADE to Interest.user_id

Revision ID: 9667cae9f7d0
Revises: 2504bd5cd76e
Create Date: 2025-07-07 02:40:45.327229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9667cae9f7d0'
down_revision: Union[str, None] = '2504bd5cd76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interests_user_id_fkey'), 'interests', type_='foreignkey')
    op.create_foreign_key(None, 'interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.create_foreign_key(op.f('interests_user_id_fkey'), 'interests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
