"""add_decline_fields_to_invitations

Revision ID: a0ea2f0b7b3a
Revises: c5a8a53fefb7
Create Date: 2024-05-27 12:00:00.000000 # Placeholder, Alembic will update

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ea2f0b7b3a'
down_revision: Union[str, None] = 'c5a8a53fefb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('declined_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('decline_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'decline_reason')
    op.drop_column('invitations', 'declined_at')
    # ### end Alembic commands ###
