"""Add attachment fields to chat_messages and conversation models

Revision ID: a9db281d289d
Revises: 25802b79acda
Create Date: 2025-05-09 11:17:48.347454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9db281d289d'
down_revision: Union[str, None] = '25802b79acda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.add_column('chat_messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('attachment_filename', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('attachment_mimetype', sa.String(), nullable=True))
    op.alter_column('chat_messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_chat_messages_recipient_id', table_name='chat_messages', if_exists=True)
    op.drop_index('ix_chat_messages_sender_id', table_name='chat_messages', if_exists=True)
    op.create_foreign_key('fk_chat_messages_conversation_id_conversations', 'chat_messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_messages_conversation_id_conversations', 'chat_messages', type_='foreignkey')
    op.create_index('ix_chat_messages_sender_id', 'chat_messages', ['sender_id'], unique=False)
    op.create_index('ix_chat_messages_recipient_id', 'chat_messages', ['recipient_id'], unique=False)
    op.alter_column('chat_messages', 'read_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chat_messages', 'attachment_mimetype')
    op.drop_column('chat_messages', 'attachment_filename')
    op.drop_column('chat_messages', 'attachment_url')
    op.drop_column('chat_messages', 'conversation_id')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
