"""add last_message to conversation

Revision ID: bbd2e8d51ecc
Revises: 33b3dd732ecc
Create Date: 2025-07-06 13:03:10.888034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd2e8d51ecc'
down_revision: Union[str, None] = '33b3dd732ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'chat_messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'last_message_id')
    op.drop_column('conversations', 'updated_at')
    # ### end Alembic commands ###
