"""add_revoked_fields_to_invitations

Revision ID: c5a8a53fefb7
Revises: 835b07ae6f4e
Create Date: 2024-05-27 10:00:00.000000 # Placeholder, Alembic will update

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a8a53fefb7'
down_revision: Union[str, None] = '835b07ae6f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('revoked_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_invitations_revoked_by_admin_id_users',
        'invitations', 'users',
        ['revoked_by_admin_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invitations_revoked_by_admin_id_users', 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'revoked_by_admin_id')
    op.drop_column('invitations', 'revoked_at')
    # ### end Alembic commands ###
