"""Add startup_id to Interest model

Revision ID: e1026b17cdf0
Revises: 934a5a4cf1f3
Create Date: 2025-07-06 15:58:10.858757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1026b17cdf0'
down_revision: Union[str, None] = '934a5a4cf1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('startup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interests', 'startups', ['startup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.drop_column('interests', 'startup_id')
    # ### end Alembic commands ###
