"""add message reactions table

Revision ID: f6faaa54ca44
Revises: a9db281d289d
Create Date: 2025-05-11 07:04:29.275231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6faaa54ca44'
down_revision: Union[str, None] = 'a9db281d289d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('message_reactions', sa.Column('emoji', sa.String(), nullable=False))
    op.drop_constraint('_user_message_emoji_uc', 'message_reactions', type_='unique')
    op.create_unique_constraint('_message_user_emoji_uc', 'message_reactions', ['message_id', 'user_id', 'emoji'])
    op.drop_column('message_reactions', 'emoji_char')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_reactions', sa.Column('emoji_char', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('_message_user_emoji_uc', 'message_reactions', type_='unique')
    op.create_unique_constraint('_user_message_emoji_uc', 'message_reactions', ['user_id', 'message_id', 'emoji_char'])
    op.drop_column('message_reactions', 'emoji')
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
